### PR TITLE
fix: include regex

### LINKED ISSUE #327: defineOptions Not work when using webpack with Vue3
https://github.com/sxzz/unplugin-vue-macros/blob/78d57f46348a43cc747b6aa17d8a4344455e8a1f/packages/define-options/src/index.ts#L22

This question is similar to [Unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus/issues/185)
I use @vue/cli-service@5 which means webpack 5
Just add `REGEX_VUE_SUB` to __options.include__ as default can fix this problem, not only Vue2 needs check transformed filename.

### PR DESCRIPTION
**Pull request by kekexunxun**
### Description

Improve auto import for project with `@vue/cli-service@5` with Vue3.

I used `unplugin-vue-define-options@1.3.3` in my project, and I need to specific the include option in my `vue.config.js` file.
```ts
UnpluginDefineOptions({ version: 3, include: [/\.setup\.[cm]?[jt]sx?$/, /\.vue$/, /\.vue\?vue&/] })
```
Just remove original Vue version 2 limited to include origin reg `REGEX_VUE_SUB` as default can solve this problem.

### Linked Issues

close #327 

### Additional context

Reproduction link https://stackblitz.com/edit/vitejs-vite-drvu4g?file=src/App.vue

### CODE REVIEW

File: packages/define-options/src/index.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ function resolveOption(
   const version = options.version || detectVueVersion()
   return {
     include: [REGEX_VUE_SFC, REGEX_SETUP_SFC].concat(
-      version === 2 && framework === 'webpack' ? REGEX_VUE_SUB : []
```
Comment (sxzz) [inline packages/define-options/src/index.ts:23]: I think we can remove them from all the packages

Comment (kekexunxun) [reply packages/define-options/src/index.ts:23]: If so, we need to change it like:

```ts
include: [REGEX_VUE_SFC, REGEX_SETUP_SFC, REGEX_VUE_SUB]
```

**Review by sxzz — APPROVED** [review]
